// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEcw2rgBLfOPKU5IBPs8Q-XhZg3XpXdTo',
    appId: '1:784879008655:web:de78416da43cd2dd9ce9fa',
    messagingSenderId: '784879008655',
    projectId: 'connectifyapp-600c8',
    authDomain: 'connectifyapp-600c8.firebaseapp.com',
    storageBucket: 'connectifyapp-600c8.firebasestorage.app',
    measurementId: 'G-97W25RW52N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClsDNO_YXFAWhUsXAIXZwCoTrsCbpEWZo',
    appId: '1:784879008655:android:8a6c565b4c90b37a9ce9fa',
    messagingSenderId: '784879008655',
    projectId: 'connectifyapp-600c8',
    storageBucket: 'connectifyapp-600c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCdVBaYliUkd9JMIzGxWunAAZ_NkuvHSc',
    appId: '1:784879008655:ios:ec7194e0d2cd5c349ce9fa',
    messagingSenderId: '784879008655',
    projectId: 'connectifyapp-600c8',
    storageBucket: 'connectifyapp-600c8.firebasestorage.app',
    iosBundleId: 'com.example.connectifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCdVBaYliUkd9JMIzGxWunAAZ_NkuvHSc',
    appId: '1:784879008655:ios:ec7194e0d2cd5c349ce9fa',
    messagingSenderId: '784879008655',
    projectId: 'connectifyapp-600c8',
    storageBucket: 'connectifyapp-600c8.firebasestorage.app',
    iosBundleId: 'com.example.connectifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEcw2rgBLfOPKU5IBPs8Q-XhZg3XpXdTo',
    appId: '1:784879008655:web:36ba23807f925a379ce9fa',
    messagingSenderId: '784879008655',
    projectId: 'connectifyapp-600c8',
    authDomain: 'connectifyapp-600c8.firebaseapp.com',
    storageBucket: 'connectifyapp-600c8.firebasestorage.app',
    measurementId: 'G-05S5TMPWZC',
  );
}
